title: app-store
appid: 7n0ixx2rkdfl
ver: 1.0.0-5
ability: cloud
alias: store/
cors:
  Access-Control-Allow-Origin: "*"
  Access-Control-Allow-Methods: "GET,POST"
  Access-Control-Allow-Headers: "Trace"
cloud:
  root: dist
  driver: ":go"
  
