
name: abi-app-store
alias: /store

services:
  abi-app-store:
    type: abi-app-store
    collection: store/
    db: abi-db
    prefix: store_
    user-svc: http://127.0.0.1:8084/user
    email-enabled: false
  abi-db:
    type: abi-db
    addr: 127.0.0.1:8082
  redis:
    type: redis
    addr: 127.0.0.1:6379
    pool-size: 200
  smtp:
    type: smtp
    from: 
    user:
    password:
    host:
    port:
  http:
    type: http
  oss:
    type: oss
    driver: aws
    region: ap-northeast-1
    bucket: app-ability-sh
    accessKey: 
    secretKey: 
    baseURL: https://app.ability.sh

