name: latest

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: env
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: ./.github/ci/build.sh
      - name: ability
        run: |
          go install github.com/ability-sh/ability@v1.0.0
          ls /root/go/bin/ability
          chmod +x /root/go/bin/ability
          export PATH=$PATH:/root/go/bin
      - name: publish
        run: ./.github/ci/publish.sh
        env:
          ABI_TOKEN: ${{ secrets.ABI_TOKEN }}

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{secrets.GITHUB_TOKEN}}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       abi-app-store
